### PR TITLE
Closes #23 - Discovery/all_tests now searches for full namespaces for…

### LINKED ISSUE #23: Discovery - all_tests - Test page is identified in multiple namespaces
I have cloned 'openui5' repo to do some hacking. My intention was to learn more about how namespaces (libraries) are created in UI5.

Then I created a library called sap.foo with a simple control called ControlA based on other libraries already available. So far so good.

My .library file inside /sap.foo/src/sap/foo folder looks like this.

```
<?xml version="1.0" encoding="UTF-8" ?>
<library xmlns="http://www.sap.com/sap.ui.library.xsd" >

  <name>sap.foo</name>
  <vendor>SAP SE</vendor>
  <copyright>${copyright}</copyright>
  <version>${version}</version>

  <documentation>SAPUI5 example library</documentation>

  <dependencies>
  
  </dependencies>

  <appData>
    
    <documentation xmlns="http://www.sap.com/ui5/buildext/documentation"
        indexUrl="../../../test-resources/sap/tnt/demokit/docuindex.json"
        resolve="lib" />
    <releasenotes xmlns="http://www.sap.com/ui5/buildext/releasenotes"
        url="../../../test-resources/sap/tnt/relnotes/changes-{major}.{minor}.json"
        resolve="lib" />

    <ownership xmlns="http://www.sap.com/ui5/buildext/ownership">
        <component></component>
    </ownership>

  </appData>

</library>
```

When visiting SAPUI5 Testsuite, I realised that my ControlA was found inside library sap.f as well.

image

After digging into the code I found Grunt, this repository and the 'discovery' middleware. 

This service really has a bug.

image

After doing more research, I found the bug inside discovery.js file:

```
eachGlobbedFile(options.testresources, '**/*.{html,htm}', function(file) {
	if (testPagesPattern.test(file)) {
		Object.keys(mLibs).forEach(function(lib) {
			if (file.indexOf(lib) === 0) {
				response.push({
					lib: mLibs[lib],
					name: file.substr(lib.length + 1),
					url: '../' + file
				});
			}
		});
	}
}
```

When comparing namespaces against test files,

file.indexOf(lib)

will return 0 when

file = 'sap/foo/ControlA.html'
lib = 'sap/foo'

but will also return 0 when 

file = 'sap/foo/ControlA.html'
lib = 'sap/f'

So this would impact any namespaces which names are prefixes of other namespaces.

My suggestion is to add a '/' in the comparison so we can guarantee that we are looking for right namespaces and not string prefixes 

In order to fix the issue, I will create a push request with such fix

### PR DESCRIPTION
**Pull request by fabiopagoti**
… each test file

### CODE REVIEW

**Comment by fabiopagoti** [comment]
https://github.com/SAP/openui5/blob/master/CONTRIBUTING.md

I don't see the link to accept the CLA

https://cla-assistant.io/ is not working at the moment

**Comment by matz3** [comment]
Thanks @fabiopagoti 👍 
Totally valid. I've extended the tests, so that this won't break in future.

I've also re-triggered the CLA check. There is now a comment with the badge that will bring you to the CLA assistant page for signing.

**Comment by fabiopagoti** [comment]
Now the CLA worked for me

**Comment by matz3** [comment]
Great 🎉

**Pull request merged**
